version: '3.5'
services:
  # drs_database:
  #   image: "postgres:11"
  #   container_name: "ag_database"
  #   ports:
  #     - "5430:5432"
  #   volumes:
  #     - ag_database

  ag_api:
    build: .
    container_name: 'ag_api'
    command: npm run api
    ports:
      - '7070:7070'
    volumes:
      - .:/src/automated-greenhouse:rw
      - /src/automated-greenhouse/node_modules
    env_file:
      - ./.env

  ag_interface:
    build: .
    container_name: 'ag_interface'
    ports:
      - 4000:4000
    volumes:
      - .:/src/automated-greenhouse:rw
      - /src/automated-greenhouse/node_modules
    command: npm run interface
    env_file:
      - ./.env
